### ISSUE TITLE
StringBuffer used in Coordinates class's toString method()

### ISSUE THREAD

**Issue by shweta-code** [priyaaank/MarsRover#1]
As I see the problem , there is no requirement of Multi-Threaded environment and also there is no such code written for it. Therefore  StringBuilder should be used as it has high slightly high performance.

**Comment by priyaaank** [comment]
Which particular section of the code do you think will benefit from an StringBuilder implementation? Can you please point me to that?

**Comment by shweta-code** [comment]
I think StringBuilder should be used.

**Comment by priyaaank** [comment]
Exactly where in the code should StringBuilder be used?

**Comment by shweta-code** [comment]
This is the piece of code:

@Override
    public String toString() {
        StringBuffer coordinateOutput = new StringBuffer();
        coordinateOutput.append(xCoordinate);
        coordinateOutput.append(" ");
        coordinateOutput.append(yCoordinate);
        return coordinateOutput.toString();
    }

**Comment by priyaaank** [comment]
Thanks. That is a reasonable suggestion. I'll make the change. Alternatively feel free to submit a pull request.

**Comment by shweta-code** [comment]
Priyank , I am not able to push. Permission denied.

![marsroverdeniedpermission](https://cloud.githubusercontent.com/assets/12433769/18463412/85bf5c14-79a7-11e6-8e7f-5c28c82fc20a.PNG)

**Comment by priyaaank** [comment]
Yes, you won't be able to push. However you can fork the repo and commit on your version of repo and submit a pull request. More info [here](https://help.github.com/categories/collaborating-on-projects-using-issues-and-pull-requests/)

**Comment by shweta-code** [comment]
I have created a pull request. https://github.com/priyaaank/MarsRover/pull/2
You can go ahead with merge.

**Comment by priyaaank** [comment]
Thank you!
